print("Lets begin the game of Madlibs!!")
print("The program will first prompt the user for a series of inputs a la Mad Libs. \n For example, a singular noun, "
      "an adjective, etc. Then, once all the information has been inputted, \n the program will take that data and "
      "place them into a pre-made story template.\n")

a = str(input("Today we are celebrating _holiday_"))
b = str(input("dinner at_relative_'s "))
c = str(input("house.When we arrived , my _relative_"))
d = str(input("Greeted us with a big _adjective_ kiss.")),
e = str(input("Kisses were so_adjective_"))
f = str(input("Now we're are just waiting for the_animal_"))
g = str(input("to come out of the oven. My dad is watching _sport_on TV."))
h = str(input("He always shout_exclamation_, "))
i = str(input("when his team scores a _noun_"))
j = str(input("Yesss _team name_--!!!"))
k = int(input("Only _minutes_"))
l = str(input("more minutes until the _animal_""will be ready!"))
m = str(input("I wonder if my mom will let me try the _animal_ "))
n = str(input("first.My grandma makes the best _flavour_"))
o = str(input("pie! It smells like a_noun_ "))
p = str(input("Happy _holiday_"))

print("TIME TO SEE THE RESULTS!!")

print("\nToday we are celebrating ", a, end='')
print(" dinner at ", b, "'s", end='')
print(" house.When we arrived , my ", c, end='')
print(" greeted us with a big ", d, end='')
print(" Kiss. Kisses were so ", e)
print("Now we're are just waiting for the ", f, end='')
print(" to come out of the oven. My dad is watching ", g, "on TV.", end='')
print("He always shout ", h, end='')
print(" when his team scores a ", i, end='')
print(" Yesss ", j, end='')
print(" \nOnly", k, end='')
print("more minutes until the ", l, "will be ready!!", end='')
print("I wonder if my mom will let me try the ", m, "first",  end='')
print(" My grandma makes the best ", n, end='')
print(" pie! It smells like a ", o)
print(" Happy ", p, "!!")
